server:
  port: ${PORT}
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: banking-core-system
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 2
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.example.bank@gmail.com
    password: ${GOOGLE_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true